use crate::ptr::RPtrRepresentable;
use js_chain_libs::*;

impl RPtrRepresentable for Account {}
impl RPtrRepresentable for AccountBindingSignature {}
impl RPtrRepresentable for AccountIdentifier {}
impl RPtrRepresentable for Address {}
impl RPtrRepresentable for Balance {}
impl RPtrRepresentable for Bip32PrivateKey {}
impl RPtrRepresentable for Bip32PublicKey {}
impl RPtrRepresentable for Certificate {}
impl RPtrRepresentable for CertificateKind {}
impl RPtrRepresentable for DelegationRatio {}
impl RPtrRepresentable for DelegationKind {}
impl RPtrRepresentable for DelegationType {}
impl RPtrRepresentable for Fee {}
impl RPtrRepresentable for Fragment {}
impl RPtrRepresentable for FragmentId {}
impl RPtrRepresentable for Hash {}
impl RPtrRepresentable for Input {}
impl RPtrRepresentable for InputOutput {}
impl RPtrRepresentable for InputOutputBuilder {}
impl RPtrRepresentable for Inputs {}
impl RPtrRepresentable for Output {}
impl RPtrRepresentable for OutputPolicy {}
impl RPtrRepresentable for Outputs {}
impl RPtrRepresentable for OwnerStakeDelegation {}
impl RPtrRepresentable for Payload {}
impl RPtrRepresentable for PayloadAuthData {}
impl RPtrRepresentable for PoolId {}
impl RPtrRepresentable for PoolRegistration {}
impl RPtrRepresentable for PoolRetirement {}
impl RPtrRepresentable for PrivateKey {}
impl RPtrRepresentable for PublicKey {}
impl RPtrRepresentable for SpendingCounter {}
impl RPtrRepresentable for StakeDelegation {}
impl RPtrRepresentable for StakeDelegationAuthData {}
impl RPtrRepresentable for Transaction {}
impl RPtrRepresentable for TransactionBindingAuthData {}
impl RPtrRepresentable for TransactionBuilder {}
impl RPtrRepresentable for TransactionBuilderSetAuthData {}
impl RPtrRepresentable for TransactionBuilderSetIOs {}
impl RPtrRepresentable for TransactionBuilderSetWitness {}
impl RPtrRepresentable for TransactionSignDataHash {}
impl RPtrRepresentable for UtxoPointer {}
impl RPtrRepresentable for Value {}
impl RPtrRepresentable for Witness {}
impl RPtrRepresentable for Witnesses {}
